# Programa Presupuesto Maestro

def main():
    print("              // PRESUPUESTO MAESTRO //          ")
    print("1. Presupuesto de Ventas")
    print("2. Determinacion del saldo de Clientes y Flujo de Entradas")
    print("3. Presupuesto de Produccion")
    print("4. Presupuesto de Requerimiento de Materiales")
    print("5. Presupuesto de Compra de Materiales")
    print("6. Determinacion del saldo de Proveedores y Flujo de Salidas")
    print("7. Presupuesto de Mano de Obra Directa")
    print("8. Presupuesto de Gastos Indirectos de Fabricacion")
    print("9. Presupuesto de Gastos de Operacion")
    print("10. Determinacion del Costo Unitario de Productos Terminados")
    print("11. Valuacion de Inventarios Finales")
    print("A. Estado de Costo de Producción y Ventas")
    print("B. Estado de Resultados")
    print("C. Estado de Flujo de Efectivo")
    print("D. Balance General")
    print("X. Terminar el programa")


def Seccion1():
    print("PRESUPUESTO DE VENTAS")
    print("Producto CL")
    print("Semestre 1")
    uav1CL = int(input("Ingrese unidades a vender Semestre 1: "))
    precio_de_ve1CL = int(input("Ingrese Precio de venta del Semestre 1: "))
    imp_de_ve1CL = (uav1CL * precio_de_ve1CL)
    print(f"Importe de venta del Semestre 1 del Producto CL es {imp_de_ve1CL}")
    print("Semestre 2")
    uav2CL = int(input("Ingrese unidades a vender del Semestre 2: "))
    precio_de_ve2CL = int(input("Ingrese Precio de venta del Semestre 2: "))
    imp_de_ve2CL = (uav2CL * precio_de_ve2CL)
    print(f"Importe de venta del Semestre 2 del Producto CL: {imp_de_ve2CL}")
    print(f"Importe de venta total del 2016: {imp_de_ve1CL + imp_de_ve2CL}")
    print("\n")

    print("Producto CE")
    print("Semestre 1")
    uav1CE = int(input("Ingrese unidades a vender Semestre 1: "))
    precio_de_ve1CE = int(input("Ingrese precio de venta Semestre 1: "))
    imp_de_ve1CE = (uav1CE * precio_de_ve1CE)
    print(f"Importe de venta del Semestre 1 del Producto CE: {imp_de_ve1CE}")
    print("Semestre 2")
    uav2CE = int(input("Unidades a vender Semestre 2: "))
    precio_de_ve2CE = int(input("Precio de venta Semestre 2: "))
    imp_de_ve2CE = (uav2CE * precio_de_ve2CE)
    print(f"Importe de venta del Semestre 2 del Producto CE: {imp_de_ve2CE}")
    print(f"Importe de venta total del 2016: {imp_de_ve1CE + imp_de_ve2CE}")
    print("\n")

    print("Producto CR")
    print("Semestre 1")
    uav1CR = int(input("Ingrese unidades a vender Semestre 1: "))
    precio_de_ve1CR = int(input("Ingrese precio de venta Semestre 1: "))
    imp_de_ve1CR = (uav1CR * precio_de_ve1CR)
    print(f"Importe de venta del Semestre 1 del Producto CR: {imp_de_ve1CR}")
    print("Semestre 2")
    uav2CR = int(input("Unidades a vender Semestre 2: "))
    precio_de_ve2CR = int(input("Precio de venta Semestre 2: "))
    imp_de_ve2CR = (uav2CR * precio_de_ve2CR)
    print(f"Importe de venta del Semestre 2 del Producto CR: {imp_de_ve2CR}")
    print(f"Importe de venta total del 2016: {imp_de_ve1CR + imp_de_ve2CR}")
    print("\n")

    totalvta1 = (imp_de_ve1CL+imp_de_ve1CE+imp_de_ve1CR)
    totalvta2 = (imp_de_ve2CL+imp_de_ve2CE+imp_de_ve2CR)
    print(f"El total de ventas Semestre 1 es: {totalvta1}")
    print(f"El total de ventas Semestre 2 es: {totalvta2}")
    print(f"El total de ventas por Semestre es de {totalvta1 + totalvta2}")

def Seccion2():
    print("DETERMINACIÓN DEL SALDO DE CLIENTES Y FLUJO DE ENTRADAS")
    saldoClientes2015 = int(input("Ingrese el saldo de la cuenta Clientes del 31 de Diciembre del 2015: "))
    ventas_2016 = int(input("Ingrese las ventas del 2016: "))
    totalClientes2016 = (saldoClientes2015 + ventas_2016)
    print(f"El total de Clientes 2016 es {totalClientes2016}")
    print(f"El 100% Por cobranza del 2015 es {saldoClientes2015}")
    print(f"El 80% por cobranza del 2016 es {ventas_2016 * 0.8}")
    entradas_2016 = (ventas_2016  + saldoClientes2015)
    print(f"-Total de Entradas 2016: {entradas_2016}")
    print(f"-Saldo de Clientes 2016: {totalClientes2016 - entradas_2016}")

def Seccion3():
    print("PRESUPUESTO DE PRODUCCIÓN")
    print("Producto CL")
    print("-Semestre 1")
    uav1CL = int(input("Unidades a vender del Semestre 1: "))
    invt_final1CL = int(input("Inventario final del Semestre 1: "))
    total_unidades1CL = (uav1CL + invt_final1CL)
    print(f"Total de unidades del Semestre 1: {total_unidades1CL}")
    print(f"Inventario inicial del Semestre 1: {invt_final1CL}")
    unidades_prodCL1 = (total_unidades1CL - invt_final1CL)
    print(f"* Unidades a producir son del Semestre 1: {unidades_prodCL1}")
    print("\n")

    print("-Semestre 2")
    uav2CL = int(input("Ingrese las unidades a vender del Semestre 2: "))
    invt_final2CL = int(input("Ingrese el inventario final del Semestre 2: "))
    total_unidades2CL = (uav2CL + invt_final2CL)
    print(f"Total de unidades del Semestre 2: {total_unidades2CL}")
    print(f"Inventario inicial del Semestre 2: {invt_final1CL}")
    unidades_prodCL2 = (total_unidades2CL - invt_final1CL)
    print(f"* Unidades a producir son del Semestre 2: {unidades_prodCL2}")
    print("\n")

    print("TOTAL DEL 2016")
    total_uds_fin = (uav1CL + uav2CL)
    print(f"* Unidades a vender en total: {total_uds_fin}")
    print(f"* Inventario final total: {invt_final2CL}")
    total_unidades = (total_uds_fin + invt_final2CL)
    print(f"Total de unidades: {total_unidades} ")
    print(f"* Inventario inicial del total es {invt_final1CL}")
    print(f"** Unidades a producir totales: {total_unidades - invt_final1CL}")
    print("\n")

    print("Producto CE")
    print("-Semestre 1")
    uavCE1 = int(input("Ingrese las unidades a vender del 1er Semestre: "))
    invt_final1CE = int(input("Ingrese el inventario final del Semestre 1: "))
    total_unidades1CE = (uavCE1 + invt_final1CE)
    print(f"* Total de unidades del Semestre 1: {total_unidades1CE}")
    print(f"* Inventario inicial del Semestre 1: {invt_final1CE}")
    unidades_prodCE1 = (total_unidades1CE - invt_final1CE)
    print(f"* Unidades a producir del Semestre 1: {unidades_prodCE1}")
    print("\n")

    print("-Semestre 2")
    uni_a_venderCE2 = int(input("Ingrese las unidades a vender del Semestre 2: "))
    invt_final2CE = int(input("Ingrese el inventario final del Semestre 2: "))
    total_unidades2CE = (uni_a_venderCE2 + invt_final2CE)
    print(f"* Total de unidades del Semestre 2: {total_unidades2CE}")
    print(f"* Inventario inicial del Semestre 2: {invt_final1CE}")
    unidades_prodCE2 = (total_unidades2CE - invt_final1CE)
    print(f"* Unidades a producir son del Semestre 2: {unidades_prodCE2}")
    print("\n")

    print("TOTAL DEL 2016")
    total_uds_finCE = (uavCE1 + uni_a_venderCE2)
    print(f"* Unidades a vender en total: {total_uds_finCE}")
    print(f"* Inventario final total: {invt_final2CE}")
    total_UnidadesCE = (total_uds_finCE + invt_final2CE)
    print(f"* Total de unidades: {total_UnidadesCE} ")
    print(f"* Inventario inicial del total: {invt_final1CE}")
    print(f"** Unidades a producir totales: {total_UnidadesCE - invt_final1CE}")
    print("\n")

    print("Producto CR")
    print("-Semestre 1")
    uavCR1 = int(input("Ingrese las unidades a vender del Semestre 1: "))
    invt_final1CR = int(input("Ingrese el inventario final del Semestre 1: "))
    total_unidades1CR = (uavCR1 + invt_final1CR)
    print(f"Total de unidades del Semestre 1: {total_unidades1CR}")
    print(f"Inventario inicial del Semestre 1: {invt_final1CR}")
    unidades_prodCR1 = (total_unidades1CR - invt_final1CR)
    print(f"Unidades a producir del Semestre 1: {unidades_prodCR1}")
    print("\n")

    print("-Semestre 2")
    uavCR2 = int(input("Ingrese las unidades a vender del Semestre 2: "))
    invt_final2CR = int(input("Ingrese el inventario final del Semestre 2: "))
    total_unidades2CR = (uavCR2 + invt_final2CR)
    print(f"* Total de unidades del Semestre 2: {total_unidades2CR}")
    print(f"* Inventario inicial del Semestre 2: {invt_final1CR}")
    unidades_prodCR = (total_unidades2CR - invt_final1CR)
    print(f"* Unidades a producir son del Semestre 2: {unidades_prodCR}")
    print("\n")

    print("TOTAL DEL 2016")
    total_uds_finCR = (uavCR1 + uavCR2)
    print(f"* Unidades a vender en total: {total_uds_finCR}")
    print(f"* Inventario final total: {invt_final2CR}")
    total_UnidadesCR = (total_uds_finCR + invt_final2CR)
    print(f"* Total de unidades: {total_UnidadesCR} ")
    print(f"* Inventario inicial del total: {invt_final1CR}")
    print(f"** Unidades a producir totales: {total_UnidadesCR - invt_final1CR}")
    print("\n")

def Seccion4():
    print("PRESUPUESTO DE REQUERIMIENTO DE MATERIALES")
    print("Producto CL")
    print("Semestre 1")
    unidades_a_prodCL1 = int(input("Ingrese las unidades a producir del Semestre 1: "))
    print("-Material A")
    requerimiento_materialA = float(input("Ingrese el requerimiento de material A: "))
    materialACL1 = (unidades_a_prodCL1 * requerimiento_materialA)
    print(f"* Total de Material A requerido: {materialACL1}")
    print("-Material B")
    requerimiento_materialB = float(input("Ingrese el requerimiento de material B: "))
    materialBCL1 = (unidades_a_prodCL1 * requerimiento_materialB)
    print(f"* Total de Material B requerido: {materialBCL1}")
    print("-Material C")
    requerimiento_materialC = float(input("Ingrese el requerimiento de material C: "))
    materialCCL1 = (unidades_a_prodCL1 * requerimiento_materialC)
    print(f"* Total de Material C requerido: {materialCCL1}")
    print("\n")

    print("Semestre 2")
    unidades_a_prodCL2 = int(input("Ingrese las unidades a producir del Semestre 2: "))
    print("-Material A")
    requerimiento_materialA2 = float(input("Ingrese el requerimiento de material A: "))
    materialACL2 = (unidades_a_prodCL2 * requerimiento_materialA2)
    print(f"* Total de Material A requerido: {materialACL2}")
    print("-Material B")
    requerimiento_materialB2 = float(input("Ingrese el requerimiento de material B: "))
    materialBCL2 = (unidades_a_prodCL2 * requerimiento_materialB2)
    print(f"* Total de Material B requerido: {materialBCL2}")
    print("-Material C")
    requerimiento_materialC2 = float(input("Ingrese el requerimiento de material C: "))
    materialCCL2 = (unidades_a_prodCL2 * requerimiento_materialC2)
    print(f"* Total de Material C requerido: {materialCCL2}")
    print("\n")

    print("TOTAL DEL 2016")
    unidades_a_prodCLT = int(input("> Suma de unidades a producir de los Semestres 1 y 2: "))
    print("-Material A")
    requerimiento_materialAT = float(input("Ingrese el requerimiento de material A: "))
    materialACLT = (unidades_a_prodCLT * requerimiento_materialAT)
    print(f"* Total de Material A requerido: {materialACLT}")
    print("-Material B")
    requerimiento_materialBT = float(input("Ingrese el requerimiento de material B: "))
    materialBCLT = (unidades_a_prodCLT * requerimiento_materialBT)
    print(f"* Total de Material B requerido: {materialBCLT}")
    print("-Material C")
    requerimiento_materialCT = float(input("Ingrese el requerimiento de material C: "))
    materialCCLT = (unidades_a_prodCLT * requerimiento_materialCT)
    print(f"* Total de Material C requerido: {materialCCLT}")
    print("\n")

    print("Producto CE")
    print("Semestre 1")
    unidades_a_prodCE1 = int(input("Ingrese las unidades a producir del Semestre 1: "))
    print("-Material A")
    requerimiento_materialACE = float(input("Ingrese el requerimiento de material A: "))
    materialACE1 = (unidades_a_prodCE1 * requerimiento_materialACE)
    print(f"* Total de Material A requerido: {materialACE1}")
    print("-Material B")
    requerimiento_materialBCE = float(input("Ingrese el requerimiento de material B: "))
    materialBCE1 = (unidades_a_prodCE1 * requerimiento_materialBCE)
    print(f"* Total de Material B requerido: {materialBCE1}")
    print("-Material C")
    requerimiento_materialCCE = float(input("Ingrese el requerimiento de material C: "))
    materialCCE1 = (unidades_a_prodCE1 * requerimiento_materialCCE)
    print(f"* Total de Material C requerido: {materialCCE1}")
    print("\n")

    print("Semestre 2")
    unidades_a_prodCE2 = int(input("Ingrese las unidades a producir del Semestre 2: "))
    print("-Material A")
    requerimiento_materialACE2 = float(input("Ingrese el requerimiento de material A: "))
    materialACE2 = (unidades_a_prodCE2 * requerimiento_materialACE2)
    print(f"* Total de Material A requerido: {materialACE2}")
    print("-Material B")
    requerimiento_materialBCE2 = float(input("Ingrese el requerimiento de material B: "))
    materialBCE2 = (unidades_a_prodCE2 * requerimiento_materialBCE2)
    print(f"* Total de Material B requerido: {materialBCE2}")
    print("-Material C")
    requerimiento_materialCCE2 = float(input("Ingrese el requerimiento de material C: "))
    materialCCE2 = (unidades_a_prodCE2 * requerimiento_materialCCE2)
    print(f"* Total de Material C requerido: {materialCCE2}")
    print("\n")

    print("TOTAL DEL 2016")
    unidades_a_prodCET = int(input("Ingrese las suma de unidades a producir de los Semestres 1 y 2: "))
    print("-Material A")
    requerimiento_materialACET = float(input("Ingrese el requerimiento de material A: "))
    MaterialACET = (unidades_a_prodCET * requerimiento_materialACET)
    print(f"* Total de Material A requerido: {MaterialACET}")
    print("-Material B")
    requerimiento_materialACET = float(input("Ingrese el requerimiento de material B: "))
    MaterialBCET = (unidades_a_prodCET * requerimiento_materialACET)
    print(f"*Total de Material B requerido: {MaterialBCET}")
    print("-Material C")
    requerimiento_materialACET = float(input("Ingrese el requerimiento de material C: "))
    MaterialCCET = (unidades_a_prodCET * requerimiento_materialACET)
    print(f"*Total de Material C requerido: {MaterialCCET}")
    print("\n")

    print("Producto CR")
    print("Semestre 1")
    unidades_a_prodCR1 = int(input("Ingrese las unidades a producir del Semestre 1: "))
    print("-Material A")
    requerimiento_materialACR = float(input("Ingrese el requerimiento de material A: "))
    MaterialACR1 = (unidades_a_prodCR1 * requerimiento_materialACR)
    print(f"* Total de Material A requerido: {MaterialACR1}")
    print("-Material B")
    requerimiento_materialBCR = float(input("Ingrese el requerimiento de material B: "))
    MaterialBCR1 = (unidades_a_prodCR1 * requerimiento_materialBCR)
    print(f"* Total de Material B requerido: {MaterialBCR1}")
    print("-Material C")
    requerimiento_materialCCR = float(input("Ingrese el requerimiento de material C: "))
    MaterialCCR1 = (unidades_a_prodCR1 * requerimiento_materialCCR)
    print(f"* Total de Material C requerido: {MaterialCCR1}")
    print("\n")

    print("Semestre 2")
    unidades_a_prodCR2 = int(input("Ingrese las unidades a producir del Semestre 2: "))
    print("-Material A")
    requerimiento_materialACR2 = float(input("Ingrese el requerimiento de material A: "))
    MaterialACR2 = (unidades_a_prodCR2 * requerimiento_materialACR2)
    print(f"* Total de Material A requerido: {MaterialACR2}")
    print("-Material B")
    requerimiento_materialBCR2 = float(input("Ingrese el requerimiento de material B: "))
    MaterialBCR2 = (unidades_a_prodCR2 * requerimiento_materialBCR2)
    print(f"* Total de Material B requerido: {MaterialBCR2}")
    print("-Material C")
    requerimiento_materialCCR2 = float(input("Ingrese el requerimiento de material C: "))
    MaterialCCR2 = (unidades_a_prodCR2 * requerimiento_materialCCR2)
    print(f"* Total de Material C requerido: {MaterialCCR2}")
    print("\n")

    print("TOTAL DEL 2016")
    unidades_a_prodCRT = int(input("> Suma de unidades a producir de los Semestres 1 y 2: "))
    print("-Material A")
    requerimiento_materialACRT = float(input("Ingrese el requerimiento de material A: "))
    MaterialACRT = (unidades_a_prodCRT * requerimiento_materialACRT)
    print(f"* Total de Material A requerido: {MaterialACRT}")
    print("-Material B")
    requerimiento_materialBCRT = float(input("Ingrese el requerimiento de material B: "))
    MaterialBCRT = (unidades_a_prodCRT * requerimiento_materialBCRT)
    print(f"* Total de Material B requerido {MaterialBCRT}")
    print("-Material C")
    requerimiento_materialCCRT = float(input("Ingrese el requerimiento de material C: "))
    MaterialCCRT = (unidades_a_prodCRT * requerimiento_materialCCRT)
    print(f"* Total de Material C requerido {MaterialCCRT}")
    print("--Total de Requerimientos (en gramos)--")
    print(f"Semestre 1 Material A = {materialACL1 + materialACE1 + MaterialACR1}")
    print(f"Semestre 1 Material B = {materialBCL1 + materialBCE1 + MaterialBCR1}")
    print(f"Semestre 1 Material C = {materialCCL1 + materialCCE1 + MaterialCCR1}")
    print("\n")
    print(f"Semestre 2 Material A = {materialACL2 + materialACE2 + MaterialACR2}")
    print(f"Semestre 2 Material B = {materialBCL2 + materialBCE2 + MaterialBCR2}")
    print(f"Semestre 2 Material C = {materialCCL2 + materialCCE2 + MaterialCCR2}")
    print("\n")
    print(f"Total Material A = {materialACLT + MaterialACET + MaterialACRT}")
    print(f"Total Material B = {materialBCLT + MaterialBCET + MaterialBCRT}")
    print(f"Total Material C = {materialCCLT + MaterialCCET + MaterialCCRT}")
    print("\n")

def Seccion5():
    print("PRESUPUESTO DE COMPRA DE MATERIALES")
    print("Material A")
    print("--Semestre 1")
    requerimiento5_matA1 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matA1 = int(input("Ingrese el inventario final: "))
    total5_matA1 = (requerimiento5_matA1 + inventariofinal_matA1)
    print(f"Total de materiales: {total5_matA1}")
    print(f"Inventario inicial: {inventariofinal_matA1}")
    mat_acomprarA1 = (total5_matA1 - inventariofinal_matA1)
    print(f"Material a comprar: {mat_acomprarA1}")
    precio_compraMatA1 = int(input("Ingrese el precio de compra: "))
    totalcompraMatA1 = (mat_acomprarA1 * precio_compraMatA1)
    print(f"Total de Material A Semestre 1: $ {totalcompraMatA1}")
    print("\n")

    print("--Semestre 2")
    requerimiento5_matA2 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matA2 = int(input("Ingrese el inventario final: "))
    total5_matA2 = (requerimiento5_matA2 + inventariofinal_matA2)
    print(f"Total de materiales: {total5_matA2}")
    print(f"Inventario Inicial: {inventariofinal_matA1}")
    mat_acomprarA2 = (total5_matA2 - inventariofinal_matA1)
    print(f"El material a comprar es: {mat_acomprarA2}")
    precio_compaMatA2 = int(input("Ingrese el precio de compra: "))
    totalcompraMatA2 = (mat_acomprarA2 * precio_compaMatA2)
    print(f"Total de Material A en Semestre 2: $ {totalcompraMatA2}")
    print("\n")

    print("TOTAL DEL 2016")
    requerimiento5_matAT = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matAT = int(input("Ingrese el inventario final: "))
    total5_matAT = (requerimiento5_matAT + inventariofinal_matAT)
    print(f"Total de materiales: {total5_matAT}")
    print(f"Inventario Inicial: {inventariofinal_matA1}")
    mat_acomprarAT = (total5_matAT - inventariofinal_matA1)
    print(f"El material a comprar es: {mat_acomprarAT}")
    totalcompraMatAT = (totalcompraMatA1 + totalcompraMatA2)
    print(f"Total de Material total: $ {totalcompraMatAT}")
    print("\n")

    print("Material B")
    print("--Semestre 1")
    requerimiento5_matB1 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matB1 = int(input("Ingrese el inventario final: "))
    total5_matB1 = (requerimiento5_matB1 + inventariofinal_matB1)
    print(f"Total de materiales: {total5_matB1}")
    print(f"Inventario inicial: {inventariofinal_matB1}")
    mat_acomprarB1 = (total5_matB1 - inventariofinal_matB1)
    print(f"El material a comprar es: {mat_acomprarB1}")
    precio_compaMatB1 = int(input("Ingrese el precio de compra: "))
    totalcompraMatB1 = (mat_acomprarB1 * precio_compaMatB1)
    print(f"Total de Material A en Semestre 1: $ {totalcompraMatB1}")
    print("\n")

    print("--Semestre 2")
    requerimiento5_matB2 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matB2 = int(input("Ingrese el inventario final: "))
    total5_matB2 = (requerimiento5_matB2 + inventariofinal_matB2)
    print(f"Total de materiales: {total5_matB2}")
    print(f"Inventario inicial: {inventariofinal_matB1}")
    mat_acomprarB2 = (total5_matB2 - inventariofinal_matB1)
    print(f"El material a comprar es: {mat_acomprarB2}")
    precio_compaMatB2 = int(input("Ingrese el precio de compra: "))
    totalcompraMatB2 = (mat_acomprarB2 * precio_compaMatB2)
    print(f"Total de Material A en Semestre 2: $ {totalcompraMatB2}")
    print("\n")

    print("TOTAL DEL 2016")
    requerimiento5_matBT = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matBT = int(input("Ingrese el inventario final: "))
    total5_matBT = (requerimiento5_matBT + inventariofinal_matBT)
    print(f"Total de materiales: {total5_matBT}")
    print(f"Inventario inicial: {inventariofinal_matB1}")
    mat_acomprarBT = (total5_matBT - inventariofinal_matB1)
    print(f"El material a comprar es: {mat_acomprarBT}")
    totalcompraMatBT = (totalcompraMatB1 + totalcompraMatB2)
    print(f"Total de Material Total: $ {totalcompraMatBT}")
    print("\n")

    print("Material C")
    print("--Semestre 1")
    requerimiento5_matC1 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matC1 = int(input("Ingrese el inventario final: "))
    total5_matC1 = (requerimiento5_matC1 + inventariofinal_matC1)
    print(f"Total de materiales: {total5_matC1}")
    print(f"Inventario inicial: {inventariofinal_matC1}")
    mat_acomprarC1 = (total5_matC1 - inventariofinal_matC1)
    print(f"El material a comprar es: {mat_acomprarC1}")
    precio_compaMatC1 = int(input("Ingrese el precio de compra: "))
    totalcompraMatC1 = (mat_acomprarC1 * precio_compaMatC1)
    print(f"Total de Material C Semestre 1: $ {totalcompraMatC1}")
    print("\n")

    print("--Semestre 2")
    requerimiento5_matC2 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matC2 = int(input("Ingrese el inventario final: "))
    total5_matC2 = (requerimiento5_matC2 + inventariofinal_matC2)
    print(f"Total de materiales: {total5_matC2}")
    print(f"Inventario inicial: {inventariofinal_matC1}")
    mat_acomprarC2 = (total5_matC2 - inventariofinal_matC1)
    print(f"El material a comprar es: {mat_acomprarC2}")
    precio_compaMatC2 = int(input("Ingrese el precio de compra: "))
    totalcompraMatC2 = (mat_acomprarC2 * precio_compaMatC2)
    print(f"Total de Material C Semestre 2: $ {totalcompraMatC2}")
    print("\n")

    print("TOTAL DEL 2016")
    requerimiento5_matCT = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matCT = int(input("Ingrese el inventario final: "))
    total5_matCT = (requerimiento5_matCT + inventariofinal_matCT)
    print(f"Total de materiales: {total5_matCT}")
    print(f"Inventario inicial: {inventariofinal_matC1}")
    mat_acomprarCT = (total5_matCT - inventariofinal_matC1)
    print(f"El material a comprar es: {mat_acomprarCT}")
    totalcompraMatCT = (totalcompraMatC1 + totalcompraMatC2)
    print(f"Total de Material: $ {totalcompraMatCT}")
    print("\n")
    comprastotalesS1 = (totalcompraMatA1 + totalcompraMatB1 + totalcompraMatC1)
    comprastotalesS2 = (totalcompraMatA2 + totalcompraMatB2 + totalcompraMatC2)
    comprastotalesT = (totalcompraMatAT + totalcompraMatBT + totalcompraMatCT)
    print(f"Compras totales Semestre 1: {comprastotalesS1}")
    print(f"Compras totales Semestre 2: {comprastotalesS2}")
    print(f"Total de Compras (Semestre 1 y 2): {comprastotalesT}")
    print("\n")


def Seccion6():
    print("DETERMINACION DEL SALDO DE PROVEEDORES Y FLUJO DE SALIDA")
    saldo_proveedores2015 = int(input("Ingrese el saldo de Proveedores del 31 de diciembre 2015: "))
    compras_2016 = int(input("Ingrese las compras del 2016: "))
    total_proveedores2016 = (saldo_proveedores2015 + compras_2016)
    print(f"El Total de Proveedores 2016: {total_proveedores2016}")
    print(f"El 100% Por cobranza del 2015: {saldo_proveedores2015}")
    cobranzaproveedores_2016 = (compras_2016 * 0.5)
    print(f"50% por cobranza del 2016: {cobranzaproveedores_2016}")
    salidasproveedores_2016 = (cobranzaproveedores_2016 + saldo_proveedores2015)
    print(f"Total de Salidas 2016: {salidasproveedores_2016}")
    print(f"Saldo de Clientes 2016: {total_proveedores2016 - salidasproveedores_2016}")


def Seccion7():
    print("PRESUPUESTO DE MANO DE OBRA DIRECTA *M.O.D.*")
    print("Producto CL")
    print("-Semestre 1")
    udsaProd1 = float(input("Ingrese las unidades a producir del Semestre 1: "))
    hrsUd1 = float(input("Ingrese las horas requeridas por unidad del Semestre 1: "))
    ttlhr1 = (udsaProd1 * hrsUd1)
    print(f"Total de horas requeridas del Semestre 1: {ttlhr1}")
    cuoph1 = float(input("Ingrese la cuota por hora del Semestre 1: "))
    impMOD = (ttlhr1 * cuoph1)
    print(f"Importe de M.O.D. del Semestre 1: {impMOD}")
    print("\n")

    print("Semestre 2")
    udsaProd2 = float(input("Ingrese las unidades a producir del Semestre 2: "))
    hrsUd2 = float(input("Ingrese las horas requeridas por unidad del Semestre 2: "))
    ttlhr2 = (udsaProd2 * hrsUd2)
    print(f"Total de horas requeridas del Semestre 2: {ttlhr2}")
    cuoph2 = float(input("Ingrese la cuota por hora del Semestre 2: "))
    impMOD2 = (ttlhr2 * cuoph2)
    print(f"Importe de M.O.D. del Semestre 2: {impMOD2}")
    print("\n")

    print("TOTAL DEL AÑO")
    udsaProdT = (udsaProd1 + udsaProd2)
    hr_p_ut = (hrsUd1)
    ttlhrt = (udsaProdT * hr_p_ut)
    impMODT = (impMOD + impMOD2)
    print(f"Total de horas requeridas del año: {ttlhrt}")
    print(f"Importe de M.O.D. del año: {impMODT}")
    print("\n")

    print("Producto CE")
    print("-Semestre 1")
    udsaProdCE1 = float(input("Ingrese las unidades a producir del Semestre 1: "))
    hrsCE1 = float(input("Ingrese las horas requeridas por unidad del Semestre 1: "))
    ttlhr1c = (udsaProdCE1 * hrsCE1)
    print(f"Total de horas requeridas del Semestre 1: {ttlhr1c}")
    cuoph1c = float(input("Ingrese la cuota por hora del Semestre 1: "))
    imdm1c = (ttlhr1c * cuoph1c)
    print(f"Importe de M.O.D. del Semestre 1: {imdm1c}")
    print("\n")

    print("-Semestre 2")
    udsaProdCE2 = float(input("Ingrese las unidades a producir del Semestre 2: "))
    hrsCE2 = float(input("Ingrese las horas requeridas por unidad del Semestre 2: "))
    ttlhr2c = (udsaProdCE2 * hrsCE2)
    print(f"Total de horas requeridas del Semestre 2: {ttlhr2c}")
    cuoph2c = float(input("Ingrese la cuota por hora del Semestre 2: "))
    imdm2c = (ttlhr2c * cuoph2c)
    print(f"Importe de M.O.D. del Semestre 2: {imdm2c}")
    print("\n")

    print("TOTAL DEL AÑO")
    un_a_ptc = (udsaProdCE1 + udsaProdCE2)
    hr_p_utc = (hrsCE1)
    ttlhrtc = (un_a_ptc * hr_p_utc)
    imdmtc = (imdm1c + imdm2c)
    print(f"Total de horas requeridas del año es: {ttlhrtc}")
    print(f"Importe de M.O.D. del año es: {imdmtc}")
    print("\n")

    print("Producto CR")
    print("-Semestre 1")
    udsaProdCR1 = float(input("Ingrese las unidades a producir del Semestre 1: "))
    hrsCR1 = float(input("Ingrese las horas requeridas por unidad del Semestre 1: "))
    ttlhr1d = (udsaProdCR1 * hrsCR1)
    print(f"Total de horas requeridas del Semestre 1 es: {ttlhr1d}")
    cuoph1d = float(input("Ingrese la cuota por hora del Semestre 1: "))
    imdm1d = (ttlhr1d * cuoph1d)
    print(f"Importe de M.O.D. del Semestre 1: {imdm1d}")
    print("\n")

    print("Semestre 2")
    udsaProdCR2 = float(input("Ingrese las unidades a producir del Semestre 2: "))
    hrsCR2 = float(input("Ingrese las horas requeridas por unidad del Semestre 2: "))
    ttlhr2d = (udsaProdCR2 * hrsCR2)
    print(f"Total de horas requeridas del Semestre 2: {ttlhr2d}")
    cuoph2d = float(input("Ingrese la cuota por hora del Semestre 2: "))
    imdm2d = (ttlhr2d * cuoph2d)
    print(f"Importe de M.O.D. del Semestre 2: {imdm2d}")
    print("\n")

    print("TOTAL DEL AÑO")
    un_a_ptd = (udsaProdCR1 + udsaProdCR2)
    hr_p_utd = (hrsCR1)
    ttlhrtd = (un_a_ptd * hr_p_utd)
    imdmtd = (imdm1d + imdm2d)
    print(f"Total de horas requeridas del año: {ttlhrtd}")
    print(f"Importe de M.O.D. del año: {imdmtd}")

    print(f"Total de horas requeridas por Semestre (1): {(ttlhr1 + ttlhr1c + ttlhr1d)}")
    print(f"Total de horas requeridas por Semestre (2): {(ttlhr2 + ttlhr2c + ttlhr2d)}")
    print(f"Total de horas requeridas por Semestre del Año: {(ttlhrt + ttlhrtc + ttlhrtd)}")

    print(f"Total de M.O.D. por Semestre (1): {(impMOD + imdm1c + imdm1d)}")
    print(f"Total de M.O.D. por Semestre (2): {(impMOD2 + imdm2c + imdm2d)}")
    print(f"Total de M.O.D. por Semestre del Año: {(impMODT + imdmtc + imdmtd)}")

def Seccion8():
    print("PRESUPUESTO DE GASTOS INDIRECTOS DE FABRICACIÓN")
    print("-Semestre 1")
    deprec1 = int(input("Depreciacion del Semestre 1: "))
    seguros1 = int(input("Costo de seguros del Semestre 1: "))
    mtnmto1 = int(input("Costo de Mantenimiento del Semestre 1: "))
    energeticos1 = int(input("Costo de energeticos del Semestre1: "))
    varios1 = int(input("Costos varios del Semestre 1: "))
    ttls1 = (deprec1 + seguros1 + mtnmto1 + energeticos1 + varios1)
    print(f"Total G.I.F. Semestre 1: {ttls1}")
    print("\n")
    print("-Semestre 2")
    deprec2 = int(input("Depreciacion del Semestre 2: "))
    seguros2 = int(input("Costo de seguros del Semestre 2: "))
    mtnmto2 = int(input("Costo de mantenimiento del Semestre 2: "))
    energeticos2 = int(input("Costo de energeticos del Semestre 2: "))
    varios2 = int(input("Costos varios del Semestre 2: "))
    ttls2 = (deprec2 + seguros2 + mtnmto2 + energeticos2 + varios2)
    print("\n")
    print("TOTAL DEL AÑO")
    dept = (deprec1 + deprec2)
    segt = (seguros1 + seguros2)
    mantt = (mtnmto1 + mtnmto2)
    enert = (energeticos1 + energeticos2)
    vart = (varios1 + varios2)
    ttlst = (dept + segt + mantt + enert + vart)
    print(f"Total G.I.F. del Semestre 2: {ttls2}")
    print(f"Total G.I.F. del Año: {ttlst}")
    print("Coeficiente para determinar el costo por hora de gastos indirectos de fabricacion")
    print(f"Total de G.I.F {ttlst}")
    totalhrsanual = int(input("Ingrese el Total de horas M.O.D. Anual: "))
    print(f"Costo por Hora de G.I.F. {ttlst/totalhrsanual} redondeado")

def Seccion9():
    print("PRESUPUESTO DE GASTOS DE OPERACIÓN")
    print("-Semestre 1")
    deprec1 = int(input("Ingrese la Depreciacion del Semestre 1: "))
    sueysal1 = int(input("Ingrese los sueldos y salarios del Semestre 1: "))
    com1 = int(input("Ingrese el costo de las comisiones del Semestre 1: "))
    varios1 = int(input("Ingrese los costos varios del Semestre 1: "))
    intpo1 = int(input("Ingrese los interes por obligaciones del Semestre 1: "))
    ttlgo1 = (deprec1 + sueysal1 + com1 + varios1 + intpo1)
    print(f"Total de Gastos de Operacion del Semestre 1: {ttlgo1}")
    print("\n")

    print("-Semestre 2")
    deprec2 = int(input("Ingrese la Depreciacion del Semestre 2: "))
    sueysal2 = int(input("Ingrese los sueldos y salarios del Semestre 2: "))
    com2 = int(input("Ingrese el costo de las comisiones del Semestre 2: "))
    varios2 = int(input("Ingrese los costos varios del Semestre 2: "))
    intpo2 = int(input("Ingrese los interes por obligaciones del Semestre 2: "))
    ttlgo2 = (deprec2 + sueysal2 + com2 + varios2 + intpo2)
    print(f"Total de Gastos de Operacion del Semestre 2: {ttlgo2}")
    print("\n")

    print("TOTAL DEL AÑO")
    dept = (deprec1 + deprec2)
    sueysalt = (sueysal1 + sueysal2)
    comt = (com1 + com2)
    vart = (varios1 + varios2)
    intpot = (intpo1 + intpo2)
    ttlgot = (dept + sueysalt + comt + vart + intpot)
    print(f"Total de Gastos de Operacion del año: {ttlgot}")

def Seccion10():
    print("-DETERMINACION DEL COSTO UNITARIO DE PRODUCTOS TERMINADOS")
    print("Para el Producto CL:")
    print("*COSTO*")
    cosCLMaterialA = 12.00
    cosCLMaterialB = 3.00
    cosCLMaterialC = 2.00
    cosCLMDO = 18.00
    cosCLGIF = 3.17
    print(f"Costo Material de Material A Producto CL: {cosCLMaterialA}")
    print(f"Costo Material de Material B Producto CL: {cosCLMaterialB}")
    print(f"Costo Material de Material C Producto CL: {cosCLMaterialC}")
    print(f"Costo Material de Mano de Obra Producto CL: {cosCLMDO}")
    print(f"Costo Material de Gasto Indirectos Producto CL: {cosCLGIF}")

    print("*CANTIDAD*")
    canCLMaterialA = 1.00
    canCLMaterialB = 0.50
    canCLMaterialC = 10.00
    canCLMDO = 2.00
    canCLGIF = 2.00
    print(f"Cantidad Material A: {canCLMaterialA}")
    print(f"Cantidad Material B: {canCLMaterialB}")
    print(f"Cantidad Material C: {canCLMaterialC}")
    print(f"Cantidad Mano de Obra: {canCLMDO}")
    print(f"Cantidad Gastos Indirectos: {canCLGIF}")

    print("*COSTO UNITARIO*")
    cuCLMaterialA = 12.00
    cuCLMaterialB = 1.50
    cuCLMaterialC = 20.00
    cuCLMDO = 36.00
    print(f"Costo Unitario Material A: {cuCLMaterialA}")
    print(f"Costo Unitario Material B: {cuCLMaterialB}")
    print(f"Costo Unitario Material C: {cuCLMaterialC}")
    print(f"Costo Unitario Mano de obra: {cuCLMDO}")
    CuCLGasIndeFab = float(input("Ingrese el costo unitario de la gastos indirectos de fabricacion: "))
    print (f"El resultado del costo unitario del producto CL es: {(cuCLMaterialA + cuCLMaterialB + cuCLMaterialC + cuCLMDO + CuCLGasIndeFab)}")
    print("\n")

    print("Para el Producto CE")
    print("*COSTO*")
    cosCEMaterialA = 12.00
    cosCEMaterialB = 3.00
    cosCEMaterialC = 3.00
    cosCEMDO = 18.00
    cosCEGIF = 3.17
    print(f"Costo Material de Material A Producto CE: {cosCEMaterialA}")
    print(f"Costo Material de Material B Producto CE: {cosCEMaterialB}")
    print(f"Costo Material de Material C Producto CE: {cosCEMaterialC}")
    print(f"Costo Material de Mano de Obra Producto CE: {cosCEMDO}")
    print(f"Costo Material de Gasto Indirectos Producto CE: {cosCEGIF}")

    print("*CANTIDAD*")
    CanCEMaterialA = float(input("Ingrese la cantidad del Material A: "))
    CanCEMaterialB = float(input("Ingrese la cantidad del Material B: "))
    CanCEMaterialC = float(input("Ingrese la cantidad del Material C: "))
    canCEMDO = float(input("Ingrese la cantidad de Mano de Obra: "))
    canCEGIF = float(input("Ingrese la cantidad de gastos indirectos: "))

    print("*COSTO UNITARIO*")
    CuCEMaterialA = float(input("Ingrese el costo unitario del Material A: "))
    CuCEMaterialB = float(input("Ingrese el costo unitario del Material B: "))
    CuCEMaterialC = float(input("Ingrese el costo unitario del Material C: "))
    cuCEMDO = float(input("Ingrese el costo unitario de la mano de obra: "))
    cuCEGIF = float (input("Ingrese el costo unitario de la gastos indirectos: "))
    print (f"El resultado del costo unitario del producto CE es: {(CuCEMaterialA + CuCEMaterialB + CuCEMaterialC + cuCEMDO + cuCEGIF)}")
    print("\n")

    print("Para el producto CR")
    print("*COSTO*")
    cosCRMaterialA = 12.00
    cosCRMaterialB = 3.00
    cosCRMaterialC = 3.00
    cosCRMDO = 18.00
    cosCRGIF = 3.17
    print(f"Costo Material de Material A Producto CR: {cosCRMaterialA}")
    print(f"Costo Material de Material B Producto CR: {cosCRMaterialB}")
    print(f"Costo Material de Material C Producto CR: {cosCRMaterialC}")
    print(f"Costo Material de Mano de Obra Producto CR: {cosCRMDO}")
    print(f"Costo Material de Gasto Indirectos Producto CR: {cosCRGIF}")

    print("*CANTIDAD*")
    CanCRMaterialA = float(input("Ingrese la cantidad del Material A: "))
    CanCRMaterialB = float(input("Ingrese la cantidad del Material B: "))
    CanCRMaterialC = float(input("Ingrese la cantidad del Material C: "))
    CanCRManoDeObra = float(input("Ingrese la cantidad de la Mano de obra: "))
    CanCRGasIndeFab = float(input("Ingrese la cantidad de gastos indirectos: "))

    print("*COSTO UNITARIO*")
    CuCRMaterialA = float(input("Ingrese el costo unitario del Material A: "))
    CuCRMaterialB = float(input("Ingrese el costo unitario del Material B: "))
    CuCRMaterialC = float(input("Ingrese el costo unitario del Material C: "))
    CuCRManoDeObra = float(input("Ingrese el costo unitario de la mano de obra: "))
    CuCRGasIndeFab = float (input("Ingrese el costo unitario de la gastos indirectos: "))
    print (f"El resultado del costo unitario del producto CE es: {(CuCRMaterialA + CuCRMaterialB + CuCRMaterialC + CuCRManoDeObra + CuCRGasIndeFab)}")
    print("\n")

def Seccion11():
    print ("VALUACION DE INVENTARIOS FINALES")
    print("Inventario Final de Materiales")

    print("* Unidades *")
    UniMatA = int(input("Ingrese Unidades de Material A: "))
    CuMatA = float(input("Ingrese el Costo Unitario Material A: "))
    costo_totalA = (UniMatA *CuMatA)
    print(f"Costo total: {costo_totalA}")

    UniMatB = int(input("Ingrese Unidades de Material B: "))
    CuMatB = float(input("Ingrese el Costo Unitario Material B: "))
    costo_totalB = (UniMatB *CuMatB)
    print(f"Costo total: {costo_totalB}")

    UniMatC = int(input("Ingrese Unidades de Material c: "))
    CuMatC = float(input("Ingrese el Costo Unitario Material C: "))
    costo_totalC = (UniMatC *CuMatC)
    print(f"Costo total: {costo_totalC}")
    print(f"Inventario final de materiales: {costo_totalA + costo_totalB + costo_totalC}")

    print("* Inventario Final de Producto Terminado *")
    PCL = int(input("Ingrese Unidades del Producto CL: "))
    CUCL = float(input("Ingrese costo unitario del Producto CL"))
    costo_CL = (PCL * CUCL)
    print(f"Costo total: {costo_CL}")
    PCE = int(input("Ingrese Unidades del Producto CE: "))
    CUCE = float(input("Ingrese costo unitario del Producto CE"))
    costo_CE = (PCE * CUCE)
    print(f"Costo total: {costo_CE}")
    PCR = int(input("Ingrese Unidades del Producto CR: "))
    CUCR = float(input("Ingrese costo unitario del Producto CR"))
    costo_CR = (PCR * CUCR)
    print(f"Costo total: {costo_CR}")
    print(f"Inventario final de Producto Terminado: {costo_CL + costo_CE + costo_CR}")

def SeccionA():
    print("/ESTADO DE COSTO DE PRODUCCION Y VENTAS/")
    salIn_mat = int(input("Ingrese el Saldo Inicial de Materiales: "))
    Compras_Mat = int(input("(+)Ingrese Compras de Materiales: "))
    mat_Disponible = (salIn_mat + Compras_Mat)
    print(f"(=)Materiales Disponibles: {mat_Disponible}")
    Invet_Final = int(input("(-)Ingrese Inventario Final de Materiales: "))
    mat_utili = (mat_Disponible - Invet_Final)
    print(f"(=)Materiales Utilizados: {mat_utili}")
    MOD = int(input("(+)Ingrese Mano de Obra Directa: "))
    GIF = int(input("(+)Ingrese Gastos de Fabricacion Indirectos: "))
    costo_prod = (mat_utili + MOD + GIF)
    print(f"(=)Costo de Produccion: {costo_prod}")
    Invet_Inicial = int(input("(+)Ingrese Inventario Inicial de Productos Terminados: "))
    tot_PDisp = (costo_prod + Invet_Inicial)
    print(f"(=)Total de Produccion Disponible: {tot_PDisp}")
    InventarioFinal_PT = int(input("(-)Ingrese Inventario Final de Productos Terminados: "))
    print(f"(=)Costo de Ventas: {tot_PDisp - InventarioFinal_PT}")

def SeccionB():
    print("/ESTADO DE RESULTADOS/")
    Ventas = int(input("Ingrese Ventas: "))
    Costo_Ventas = int(input("Ingrese Costo de Ventas: "))
    utilidad_bruta = (Ventas - Costo_Ventas)
    print(f"(=) Utilidad Bruta: {utilidad_bruta}")
    gastos_oper = int(input("Ingrese Gastos de Operacion: "))
    utilidad_oper = (utilidad_bruta - gastos_oper)
    print(f"(=) Utilidad de Operacion: {utilidad_oper}")
    ISR = int(input("Ingrese ISR: "))
    PTU = int(input("Ingrese PTU: "))
    print(f"Utilidad Neta: {utilidad_oper - ISR - PTU}")

def SeccionC():
    print("/ESTADO DE FLUJO DE EFECTIVO/")
    SaldoInicial = float(input("Ingrese el saldo inicial: "))
    Cobranza2016 = float(input("Ingrese la cantidad de la cobranza del año 2016: "))
    Cobranza2015 = float(input("Ingrese la cantidad de la cobranza del año 2015: "))
    print (f"Total de entradas: {(Cobranza2016 + Cobranza2015 )}")
    efec_disponible = (Cobranza2016 + Cobranza2015 + SaldoInicial)
    print(f"Efectivo Disponible: {efec_disponible}")

    Provedores2016 = float(input("Ingrese el saldo de Provedores en 2016: "))
    Provedores2015 = float(input("Ingrese el saldo de Provedores en 2015: "))
    pagoMOD = float(input("Ingrese el presupuesto de Mano de Obra Directa: "))
    pagGIF = float(input("Ingrese el presupuesto de Gastos Indirectos de Fabricacion: "))
    PagoGasOperacion = float(input("Ingrese el presupuesto de gastos de operacion: "))
    CompraActivoFijo = float(input("Ingrese la cantidad de Compra de Activo Fijo: "))
    PagoISR2015 = float(input("Ingrese el pago ISR del año 2015: "))
    total_salidas = (Provedores2016 + Provedores2015 + pagoMOD + pagGIF + PagoGasOperacion + CompraActivoFijo + PagoISR2015)
    print(f"Total de salidas: {total_salidas}")
    print(f"Flujo de Efectivo Actual: {efec_disponible - total_salidas}")

def SeccionD():
    print("/BALANCE GENERAL/")
    print("*ACTIVOS*")
    print("Circulantes")
    efectivo = float(input("Ingrese el efectivo: "))
    clientes = float(input("Ingrese el valor de clientes: "))
    deu_div = float(input("Ingrese el valor de deudores diversos: "))
    funyemp = float(input("Ingrese el valor de funcionarios y empleados: "))
    invdm = float(input("Ingrese el valor de inventario de materiales: "))
    invdpt = float(input("Ingrese el valor de inventario de producto terminado: "))
    act_circulante = (efectivo + clientes + deu_div + funyemp + invdm + invdpt)
    print(f"El total de activos circulantes es: {act_circulante}")
    print("\n")

    print("No Circulantes")
    terrenos = float(input("Ingrese el terreno: "))
    pye = float(input("Ingrese el valor de planta y equipo: "))
    deprec_acum = float(input("Ingrese el valor de depreciacion acumulada: "))
    act_no_circulante = (terrenos + pye + deprec_acum)
    print(f"El total de activos no circulantes es: {act_no_circulante}")
    print("\n")
    total_activos = (act_circulante + act_no_circulante)
    print(f"El total de activos es: {total_activos}")
    print("\n")

    print("*PASIVOS*")
    print("Corto Plazo")
    proveedores = float(input("Ingrese el valor de proveedores: "))
    docpp = float(input("Ingrese el valor de documentos por pagar: "))
    isrpp = float(input("Ingrese el valor de ISR por pagar: "))
    ptupp = float(input("Ingrese el valor de PTU por pagar: "))
    pas_corto_plazo = (proveedores + docpp + isrpp + ptupp)
    print(f"El total de pasivos corto plazo es: {pas_corto_plazo}")
    print("\n")

    print("Largo Plazo")
    obligpp = float(input("Ingrese el valor de obligaciones por pagar: "))
    pas_largo_plazo = (obligpp)
    print(f"El total de pasivos largo plazo es: {pas_largo_plazo}")
    print("\n")

    total_pasivos = (pas_corto_plazo + pas_largo_plazo)
    print(f"El total de pasivo es: {total_pasivos}")
    print("\n")

    print("*CAPITAL CONTABLE*")
    capital_aportado = float(input("Ingrese el valor de capital aportado: "))
    capital_ganado = float(input("Ingrese el valor de capital ganado: "))
    utilidad_ejercicio = float(input("Ingrese el valor de utilidad del ejercicio: "))
    total_capital = (capital_aportado + capital_ganado + utilidad_ejercicio)
    print(f"El total de capital contable es: {total_capital}")
    print("\n")
    pasivo_mas_capital = (total_capital + total_pasivos)
    print(f"El total de la suma de pasivo y capital es: {pasivo_mas_capital}")


while True:
    print("\n")
    main()
    eleccion = input("Ingrese su eleccion: ")
    if eleccion == "1":
        print("\n")
        Seccion1()
    elif eleccion == "2":
        print("\n")
        Seccion2()
    elif eleccion == "3":
        print("\n")
        Seccion3()
    elif eleccion == "4":
        print("\n")
        Seccion4()
    elif eleccion == "5":
        print("\n")
        Seccion5()
    elif eleccion == "6":
        print("\n")
        Seccion6()
    elif eleccion == "7":
        print("\n")
        Seccion7()
    elif eleccion == "8":
        print("\n")
        Seccion8()
    elif eleccion == "9":
        print("\n")
        Seccion9()
    elif eleccion == "10":
        print("\n")
        Seccion10()
    elif eleccion == "11":
        print("\n")
        Seccion11()
    elif eleccion.upper() == "A":
        print("\n")
        SeccionA()
    elif eleccion.upper() == "B":
        print("\n")
        SeccionB()
    elif eleccion.upper() == "C":
        print("\n")
        SeccionC()
    elif eleccion.upper() == "D":
        print("\n")
        SeccionD()
    elif eleccion.upper() == "X":
        print("\n")
        print("Saliendo...")
        break
    else:
        print("Eleccion no valida.")
